version: '2'

services:
  # Define a HOMER service
  homer:
    image: qxip/homer-metric-all:latest
    environment:
      DO_MYSQL_STATS: 1
      ELASTICSEARCH_URL: admin:admin@elastic:9200
      DO_ELASTICSEARCH: 1
      DO_KPI: 1
      DO_GEO: 1
      DO_KAMSTAT: 1
      DO_METHOD: 1
    volumes:
      - ./data/homer/mysql:/var/lib/mysql
    ports:
      - "9060:9060/udp"
      - "8080:80"
# Define Elasticsearch service
  elastic:
    depends_on:
      - "homer"
    image: qxip/docker-kibi-steroids:latest
    environment:
      ES_USER: admin
      ES_PASSWORD: admin
     volumes:
      - ./data/elasticsearch:/var/lib/elasticsearch
     ports:
      - "9200:9200"
      - "5606:5606"
